---
title: "SEM Course - Final Project"
author: "Noa Valansi & Tomer Zipori"
format: html
editor: visual
---

# Setup

```{r}
library(tidyverse)
library(lavaan)
library(ggfortify)
library(tidySEM)
```

```{r}
data <- read.csv("../final/MentalHealthSurvey.csv")

data_clean <- data |>
  select(where(is.numeric)) |>
  mutate(isolation_rev = max(isolation) - isolation)
```

Latent variables - Lifestyle factors * Clinical measurements = Functional assessment/ADL

```{r}
meaurement_model <- '
  ## latent variable definitions (CFA)
  Stress =~ academic_workload + academic_pressure
  Well_being =~ depression + anxiety

  ## Covariances
  Well_being ~~ Stress

  ## Regressions
   
  ## errors
   
  ## autocorrelations
  
  ## self-regression (do not forget!)
'
```

```{r}
fit_meas <- cfa(meaurement_model, data = data_clean)

summary(fit_meas, fit.measures = TRUE, standardize = F)
```

```{r}
fitMeasures(fit_meas, output = "text",
            fit.measures = c("nfi","nnfi","tli","cfi","gfi","rmsea"))
```

```{r}
anova(fit_meas)
```

```{r}
modificationindices(fit_meas, sort. = TRUE, maximum.number = 5)
```

```{r}
semTools::reliability(fit_meas)
```


```{r}
lay <- get_layout(
  "Visual_perception", "Cubes", NA, "Paragraph_comprehension", "Sentence_completion", "Word_meaning", NA, "Speeded_addition", "Speeded_counting_of_dots", "Speeded_discrimination_straight_and_curved_capitals",
  "Visual",   NA,  NA,  "Language", NA, NA, NA,"Speed", NA,
  "age",
  rows = 2
)
```

```{r}
graph_sem(fit_meas, angle = 90)
```

# Mediation

## Hypothesized model

```{r}
hypothesized_model <- '
  ## latent variable definitions (CFA)
  Stress =~ academic_workload + academic_pressure
  Well_being =~ depression + anxiety

  ## Covariances

  ## Regressions
  Well_being ~ Stress
  study_satisfaction ~ Stress + Well_being
   
  ## effects
   
  ## autocorrelations
  
  ## self-regression (do not forget!)
'
```

```{r}
hypothesized_fit <- sem(hypothesized_model, data = data_clean)
```

```{r}
summary(hypothesized_fit)
```

```{r}
anova(hypothesized_fit)
```

```{r}
graph_sem(hypothesized_fit,
          edges = get_edges(hypothesized_fit, label = "est_std"),
          angle = 90)
```

## Only Stress

```{r}
strict_hypothesized_model <- '
  ## latent variable definitions (CFA)
  Stress =~ academic_workload + academic_pressure
  Well_being =~ depression + anxiety

  ## Covariances
  Well_being ~~ 0 * study_satisfaction

  ## Regressions
  Well_being ~ Stress
  study_satisfaction ~ Stress
   
  ## effects
   
  ## autocorrelations
  
  ## self-regression (do not forget!)
'
```

```{r}
strict_hypothesized_fit <- sem(strict_hypothesized_model, data = data_clean)
```

```{r}
summary(strict_hypothesized_fit)
```

```{r}
anova(strict_hypothesized_fit)
```

```{r}
graph_sem(strict_hypothesized_fit,
          edges = get_edges(strict_hypothesized_fit, label = "est_std"),
          angle = 90)
```

```{r}
anova(hypothesized_fit, strict_hypothesized_fit)
```

